### ISSUE TITLE
Front end confusing and seems out of date

### ISSUE THREAD

**Issue by ridingmower** [Resgrid/BigBoard#48]
Hello is there an easy to use front end for Resgrid user interactivity and setup to upload resources? While we see bigboard in the docs, but that seems to be a dashboard mainly and over 5 yrs old. Is this no longer maintained.

Can you share some help on the front end, and also options to suggest features and pull requests to the backend if we customize or add something..

before I loose all my hair and gave up hahahahaa chiming in..

1. Self hosted Front end, how to?
  2.     are razor views hostable? or what is the front & process for a fire fighter to upload information
3. Adding new features or code, how to, and PR or review process?
4. is there an update to big board

**Comment by ucswift** [comment]
@ridingmower BigBoard is maintained, I'm working on a new update for it now. The BigBoard is just intended for a read-only, real-time view into the department for display on a monitor or tv. I've attached a picture of the work-in-progess update for it.

The Resgrid Core application https://github.com/Resgrid/Core contains front end for uploading and managing the application, it's the https://hub.docker.com/r/resgridllc/resgridwebcore docker image. Note, all of our hosted applications (BigBoard, Disaptch) will only be distributed via Docker images. You can use the Resgrid Unit and Resgrid Responder apps in the store and point them to your own self-hosted version of Resgrid as well.

![image](https://user-images.githubusercontent.com/410646/218279618-5737d93d-3c51-4d8b-86e0-8be0729f7b12.png)
